
# ========= genesis =========
num_envs: 1     
drone_num: 1
dt: 0.01
max_vis_FPS: 15 
max_dis_num: 5
cam_quat: [-0.455, -0.542, 0.542, 0.455]  # FPV camera, 70.0 degree, show in https://quaternions.online/
cam_res: [16, 12]                         # width, height
drone_init_pos: [-0.6, 0.0, 0.4]          # Initial position of the drone
use_FPV_camera: True
vis_waypoints: True 
viewer_follow_drone: False
load_map: False
use_rc: False
show_viewer: True
render_cam: False
controller: "angle"
map: "gates"







