batch_size: 64
cam_angle: 20
coef_bias: 0.0
coef_collide: 5.0
coef_d_acc: 0.01
coef_d_jerk: 0.001
coef_d_snap: 0.0
coef_ground_affinity: 0.0
coef_obj_avoidance: 2.0
coef_speed: 0.0
coef_v: 1.0
coef_v_pred: 2.0
fov_x_half_tan: 0.82
gate: false
grad_decay: 0.4
ground_voxels: true
lr: 0.001
no_odom: false
num_iters: 50000
random_rotation: true
resume: null
scaffold: false
single: true
speed_mtp: 4.0
timesteps: 150
yaw_drift: true
