

yaw_lambda: -10.0 
reward_scales:
  target: 10.0 
  smooth: -0.0001 
  yaw: 0.01 
  angular: -0.0002
  crash: -10.0 
  lazy: -1

termination_if_roll_greater_than: 180   # degree
termination_if_pitch_greater_than: 180 
termination_if_close_to_ground: 0.1 
termination_if_x_greater_than: 3.0 
termination_if_y_greater_than: 3.0 
termination_if_z_greater_than: 2.0 

clip_actions: 1.0 
target_thr: 0.1
episode_length_s: 15.0 
max_episode_length: 1500
num_actions: 4                  # roll, pitch, yaw, thrust
num_commands: 3                 # 3d position: x, y, z
num_obs: 17                     # pos*3, quat*4, vel*3, ang_rate*3, last_actiopn*4 
obs_scales:
  cur_pos_error: 0.3333333333333333   # 1 / 3.0 
  lin_vel: 0.3333333333333333   # 1 / 3.0 
  ang_vel: 0.3183098861837907   # 1 / 3.14159 