
ang:
  kp_r: 5500.0
  ki_r: 0.0
  kd_r: 0.0
  kf_r: 0.0

  kp_p: 5500.0
  ki_p: 0.0
  kd_p: 0.0
  kf_p: 0.0

  kp_y: 3500.0
  ki_y: 0.0
  kd_y: 0.0
  kf_y: 0.0

rat:
  kp_r: 4500.0
  ki_r: 1.0
  kd_r: 100.0
  kf_r: 0.0

  kp_p: 4500.0
  ki_p: 1.0
  kd_p: 100.0
  kf_p: 0.0

  kp_y: 2500.0
  ki_y: 1.0
  kd_y: 100.0
  kf_y: 0.0

pos:
  kp_x: 4500.0
  ki_x: 0.0
  kd_x: 0.0
  kf_x: 0.0

  kp_y: 4500.0
  ki_y: 0.0
  kd_y: 0.0
  kf_y: 0.0

  kp_t: 2000.0
  ki_t: 0.0
  kd_t: 0.0
  kf_t: 0.0

pid_exec_freq: 60
base_rpm: 14468.429183500699
use_RC: True
weight: 500.0    # unit is grams 
inertia_matrix:
  - [0.005, 0.0,   0.0,  0.0]
  - [0.0,   0.005, 0.0,  0.0]
  - [0.0,   0.0,   0.009,0.0]
  - [0.0,   0.0,   0.0,  1.0]

# =========== mavlink_param =============
USB_path: "/dev/ttyUSB0"
baudrate: 2000000

ARM:       "ch5"
ANGLE:     "ch6"
OFFBOARD:  "ch8"
YAW:       "ch3" 
PITCH:     "ch2"
ROLL:      "ch1"
THRUTTLE:  "ch4"   

# =========== odom_param =============
gyro_update_freq: 8000
att_update_freq: 100
acc_update_freqL: 1000